ReservationServiceProject/ReservationService/urls.py
from django.urls import path, re_path, include
from . import views
from .models import SemesterOptions

re_semesters = f'(?P<semester>{"|".join(SemesterOptions.values)})'
re_academic_year = r'(?P<academic_year>[0-9_]{9})'

urlpatterns = [
    path('', views.home),
    path('home/', views.home, name='home'),
    path('booked/', views.booked_slots, name='index'),
    path('upload/', views.upload_csv, name='upload_csv'),
    path('classrooms_upload/', views.upload_classrooms, name='upload_classrooms'),
    path('profile/', views.profile_view, name='profile'),
    path('accept_reservations/', views.accept_reservations_view, name='accept'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('reservation/', views.reservation, name='reservation'),
    re_path(f'calendar/{re_academic_year}/{re_semesters}/', views.calendar, name='calendar_view'),
]
app_name = 'ReservationService'

ReservationServiceProject/ReservationServiceProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ReservationService.urls')),
]

ReservationServiceProject/ReservationService/models.py
from django.db import models


# Create your models here.


class SemesterOptions(models.TextChoices):
    winter = 'winter', 'winter'
    summer = 'summer', 'summer'


class ClassTypes(models.TextChoices):
    lecture = 'lecture', 'lecture hall'
    computers = 'computers', 'classroom with computers'
    board = 'board', 'normal class with board only'


class ClassName(models.Model):
    class_name = models.CharField(max_length=10, unique=True)
    class_size = models.IntegerField(default=30)
    class_type = models.CharField(choices=ClassTypes.choices, default='board', max_length=10)

    def __str__(self):
        return self.class_name.__str__() + " seats: " + self.class_size.__str__()


class ClassroomReservation(models.Model):
    # class_name = models.CharField(max_length=10)
    class_name = models.ForeignKey(ClassName, on_delete=models.CASCADE)
    # reserved_from = models.DateField('Reservation starts')
    # reserved_until = models.DateField('Reservation ends')

    time_start = models.TimeField('time class start (for now assuming that class duration is 1.5h)',
                                  auto_now=False,
                                  auto_now_add=False)

    time_end = models.TimeField('time class ends',
                                auto_now=False,
                                auto_now_add=False)  # (unused) to use this field check view.upload_csv and change
    # upload scheme

    is_regular = models.BooleanField("If it's regular classes. Default to regular classes.", default=True)
    is_AB = models.BooleanField("If it's A/B classes.")

    # maybe it's better to somehow create Person entry and store this hear to encapsulate e-mail, phone, etc.
    reserved_by = models.CharField(max_length=50,
                                   blank=True)  # (unused) for now name of the person who reserved this classroom

    academic_year = models.CharField(max_length=9)  # example: 2018/2019, maybe some validation?
    semester = models.CharField(max_length=6, choices=SemesterOptions.choices)

    def __str__(self):
        return f'class {self.class_name} is occupied at {self.time_start.__str__()} - {self.time_end.__str__()}' \
               f' by {self.reserved_by}'
        # from {self.reserved_from.__str__()} until {self.reserved_until.__str__()}'

    def save(self, *args, **kwargs):
        print('args', args)
        print('kwargs', kwargs)

        super(ClassroomReservation, self).save(*args, **kwargs)

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(semester__in=SemesterOptions.values),
                name="%(app_label)s_%(class)s_semester_valid",
            )
        ]


class ReservationDate(models.Model):
    reservation = models.ForeignKey(ClassroomReservation, on_delete=models.CASCADE)
    date = models.DateField('Reservation date')

    def __str__(self):
        return self.date.__str__()


class ClassroomReservationAttempts(models.Model):
    class_name = models.ForeignKey(ClassName, on_delete=models.CASCADE)
    reservation_date = models.DateField('Reservation date')
    time_start = models.TimeField('time class start (for now assuming that class duration is 1.5h)',
                                  auto_now=False,
                                  auto_now_add=False)

    time_end = models.TimeField('time class ends',
                                auto_now=False,
                                auto_now_add=False)
    reserved_by = models.CharField(max_length=50, blank=True)
    academic_year = models.CharField(max_length=9)
    semester = models.CharField(max_length=6, choices=SemesterOptions.choices)

    def __str__(self):
        return self.class_name.class_name + ' at ' + self.reservation_date.__str__() + ' ' + self.time_start.__str__() + \
               ' - ' + self.time_end.__str__() + ' reserved by ' + self.reserved_by.__str__()

ReservationServiceProject/ReservationService/forms.py
from django import forms

from ReservationService.models import ClassroomReservation, ClassTypes, ClassName
from django.contrib.auth.models import User
import datetime as dt


class OccupiedSlotsForm(forms.Form):
    class_name = forms.CharField(max_length=10)


class SpecificClassReservationFrom(forms.Form):
    class_name = forms.ModelChoiceField(queryset=ClassName.objects.all())


class DataInput(forms.DateInput):
    input_type = 'date'


class ReservationForm(forms.ModelForm):
    # class_name = forms.CharField(required=False)
    TIME_CHOICES_BEGIN = (
        (dt.time(hour=8, minute=0), "8:00"),
        (dt.time(hour=9, minute=35), "9:35"),
        (dt.time(hour=11, minute=15), "11:15"),
        (dt.time(hour=12, minute=50), "12:50"),
        (dt.time(hour=14, minute=40), "14:40"),
        (dt.time(hour=16, minute=15), "16:15")
    )
    TIME_CHOICES_END = (
        (dt.time(hour=9, minute=30), "9:30"),
        (dt.time(hour=11, minute=5), "11:05"),
        (dt.time(hour=12, minute=45), "12:45"),
        (dt.time(hour=14, minute=20), "14:20"),
        (dt.time(hour=16, minute=10), "16:10"),
        (dt.time(hour=17, minute=45), "17:45")
    )
    date_of_class = forms.DateField(widget=DataInput)
    start_of_booking = forms.ChoiceField(choices=TIME_CHOICES_BEGIN)
    end_of_booking = forms.ChoiceField(choices=TIME_CHOICES_END)
    seats = forms.IntegerField(min_value=0, max_value=1000, initial=0)
    class_type = forms.ChoiceField(choices=([(None, '--------')] + ClassTypes.choices)
                                   , initial={None, '--------'})

    class Meta:
        model = ClassroomReservation
        fields = ('class_name',)

    def __init__(self, *args, **kwargs):
        super(ReservationForm, self).__init__(*args, **kwargs)
        self.fields['class_name'].required = False
        self.fields['seats'].required = False
        self.fields['class_type'].required = False

    def clean(self):
        cleaned_data = super(ReservationForm, self).clean()
        begin = cleaned_data.get('start_of_booking')
        end = cleaned_data.get('end_of_booking')
        if begin > end:
            raise forms.ValidationError('Start time is after end time')


class ReservationFilterForm(forms.Form):
    begin_date = forms.DateField(widget=DataInput)
    end_date = forms.DateField(widget=DataInput)
    reserved_by = forms.ModelChoiceField(
        queryset=User.objects.all()
    )

    def __init__(self, *args, **kwargs):
        super(ReservationFilterForm, self).__init__(*args, **kwargs)
        self.fields['begin_date'].required = False
        self.fields['end_date'].required = False
        self.fields['reserved_by'].required = False

ReservationServiceProject/ReservationService/views.py
from ast import literal_eval

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import ClassroomReservation, ClassName, ReservationDate
from .forms import OccupiedSlotsForm, ReservationForm, SpecificClassReservationFrom, ReservationFilterForm
import pandas as pd


# Create your views here.
from .profile_functions import get_my_reservations, get_my_waiting_reservations, delete_waiting_reservation, \
    delete_reservation
from .reservation_functions import get_available_classes, create_reservation_attempt
from .accept_functions import process_request


def home(request):
    available_semesters = list(ClassroomReservation.objects.values_list('academic_year', 'semester').distinct())
    available_semesters.sort(key=lambda x: x[0]+x[1], reverse=True)
    tmp = []

    for year, semester in available_semesters:
        if len(tmp) != 0 and tmp[-1][0] == year:
            tmp[-1][1].append(semester)
        else:
            tmp.append((year, [semester]))
    tmp = [(x.replace('/', '_'), y) for x, y in tmp]
    return render(request, "ReservationService/home.html", {'available_semesters': tmp})


@login_required
def profile_view(request):
    data_base_respond = None
    request_type = None
    print(request.POST)
    if request.POST:
        if 'reservation' in request.POST:
            request_type = 'reservation'
            data_base_respond = get_my_reservations(request.user)
            # print(data_base_respond)
        elif 'waiting' in request.POST:
            request_type = 'waiting'
            data_base_respond = get_my_waiting_reservations(request.user)
        elif 'to_delete' in request.POST:
            if request.POST['type'] == 'waiting':
                delete_waiting_reservation(request.POST['to_delete'])
                data_base_respond = get_my_waiting_reservations(request.user)
                request_type = 'waiting'
            else:
                delete_reservation(request.POST['to_delete'])
                data_base_respond = get_my_reservations(request.user)
                request_type = 'reservation'
    return render(request, "registration/profile.html", {'content': data_base_respond, 'type': request_type})


@login_required
def reservation(request):
    if request.POST and 'additional_data' in request.POST:
        create_reservation_attempt(request.POST.dict(), request.user)
        return render(request, "ReservationService/reservation.html", {'form': ReservationForm()})
    else:
        available_classes = ()
        form = ReservationForm(request.POST or None)
        if form.is_valid():
            form2 = SpecificClassReservationFrom()
            available_classes = get_available_classes(request.POST.dict())
            form2.fields['class_name'].choices = [(obj.class_name, obj) for obj in available_classes]
        context = {'form': form, 'available_class': available_classes}
    return render(request, "ReservationService/reservation.html", context)


@staff_member_required
def accept_reservations_view(request):
    reserved = None
    attempts = None
    overlapping = None
    if request.method == 'POST':
        reservation_filter_form = ReservationFilterForm(request.POST)
        attempts, overlapping = process_request(request)
    else:
        reservation_filter_form = ReservationFilterForm()
    context = {
        'attempts': attempts,
        'overlapping': overlapping,
        'error_already_reserved': reserved,
        'filter_form': reservation_filter_form
    }
    return render(request, "ReservationService/accept_reservations.html", context)


def booked_slots(request):
    form = OccupiedSlotsForm(request.POST or None)
    class_name = None
    if form.is_valid():
        class_name = request.POST['class_name']

        form = OccupiedSlotsForm()

    booked_slots_of_the_class = ClassroomReservation.objects.filter(class_name=class_name)

    available_class = ClassroomReservation.objects.values_list('class_name', flat=True).distinct()

    context = {
        'all_booked_slots': booked_slots_of_the_class,
        'form': form,
        'available_class': available_class
    }
    return render(request, "ReservationService/booked_slots.html", context)


def _validate_and_choose_columns(classes_df):
    required_columns = ['class_name', 'time_start', 'time_end',
                        'is_AB', 'academic_year', 'semester', 'reservations']

    for col in required_columns:
        if col not in classes_df:
            return False, None

    return True, 'time_end' in required_columns


@staff_member_required
def upload_csv(request):
    template = 'ReservationService/upload_csv.html'

    context = {
        'message': 'Upload CSV in following format: TODO',  # TODO: extract string constants to separate file
    }

    if request.method == 'GET':
        return render(request, template, context)

    csv_file = request.FILES['file']

    if not csv_file.name.endswith('.csv'):
        context['error_message'] = 'file should have .csv extension'
        return render(request, template, context)

    classes_df = pd.read_csv(csv_file.name, index_col=0, converters={'reservations': literal_eval})
    is_valid, use_time_end = _validate_and_choose_columns(classes_df)

    if not is_valid:
        context['error_message'] = "file doesn't contain required columns"
        return render(request, template, context)

    columns = classes_df.columns

    redirect_year, redirect_semester = None, None

    for row in classes_df.itertuples(index=False):
        data = dict(zip(columns, row))
        reservations = data.pop('reservations')
        redirect_year = data['academic_year']
        redirect_semester = data['semester']
        data['class_name'] = ClassName.objects.get(class_name=data['class_name'])
        reservation_object, created = ClassroomReservation.objects.get_or_create(**data)
        if created:
            for date in reservations:
                ReservationDate.objects.get_or_create(reservation=reservation_object, date=date)

    redirect_year = redirect_year.replace('/', '_')

    return HttpResponseRedirect(reverse('ReservationService:calendar_view', args=(redirect_year, redirect_semester, )))


@staff_member_required
def upload_classrooms(request):
    template = 'ReservationService/upload_csv.html'

    context = {
        'message': 'Upload CSV in following format: classroom_name,class_type,class_size',  # TODO: extract string constants to separate file
    }

    if request.method == 'GET':
        return render(request, template, context)

    csv_file = request.FILES['file']

    if not csv_file.name.endswith('.csv'):
        context['error_message'] = 'file should have .csv extension'
        return render(request, template, context)

    classrooms_pd = pd.read_csv(csv_file.name, index_col=0)
    columns = classrooms_pd.columns

    for row in classrooms_pd.itertuples(index=False):
        data = dict(zip(columns, row))

        class_type = None
        if 'l' in data['class_type']:
            class_type = ClassTypes.lecture
        elif 'c' in data['class_type']:
            class_type = ClassTypes.computers
        elif 'b' in data['class_type']:
            class_type = ClassTypes.board

        ClassName.objects.get_or_create(class_name=data['class_name'], class_size=data['class_size'], class_type=class_type)

    return HttpResponseRedirect(reverse('ReservationService:reservation'))


def calendar(request, academic_year, semester):
    template = 'ReservationService/calendar_view.html'

    academic_year = academic_year.replace('_', '/')

    print(academic_year, semester)
    reservation_list_for_semester = ClassroomReservation.objects.filter(academic_year=academic_year, semester=semester)

    return render(request, template, {'reservation_list': reservation_list_for_semester})

ReservationServiceProject/ReservationService/templates/ReservationService/accept_reservations.html
{% extends 'ReservationService/base.html' %}
<head>
    <script src="sorttable.js"></script>
    <title>Reservation Accept</title>
</head>

{% block title %} Reservation Accept {% endblock %}
{% block content %}
    <div class="container" style="display: flex; ">
        <div style="width: 10%; background: grey;
            margin: 5px; height: 100%; padding: 15px">
            <form method="POST"> {% csrf_token %}
            {{ filter_form.as_p }}
                <input type="submit" value="Search" name="search">
            </form>
        </div>
        <div style="width: 45%;">
            {% if error_already_reserved.0 %}
                There is already reserved: {{ error_already_reserved.0 }}<br>
                <form method="POST"> {% csrf_token %}
                    <input type="hidden" value="{{ error_already_reserved }}" name="data">
                    <input type="submit" value="OK" name="OK">
                    <input type="submit" value="SWAP" name="SWAP">
                    <input type="submit" value="REMOVE ATTEMPT" name="REMOVE">
                </form>
            {% endif %}
            Reservation attempts:
            <table class="sortable" style="width:90%" border=1 frame=void rules=rows>
                <thead>
                    <tr>
                    <th>Class number</th>
                    <th>Reservation date</th>
                    <th>Start time</th>
                    <th>End time</th>
                    <th>Reserved by</th>
                    </tr>
                </thead>
                <tbody>
                {% for attempt in attempts %}
                    <form method="POST"> {% csrf_token %}
                    <tr>
                        <td>{{ attempt.class_name.class_name }}</td>
                        <td>{{ attempt.reservation_date }}</td>
                        <td>{{ attempt.time_start }}</td>
                        <td>{{ attempt.time_end }}</td>
                        <td>{{ attempt.reserved_by }}</td>
                        <td><input type="submit" value="accept" name="accept_button"></td>
                        <td> <input type="hidden" value="{{ attempt.id }}" name="attempt"></td>
                    </tr>
                    </form>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div>
            Conflicts:
            <table class="sortable" style="width:90%" border=1 frame=void rules=rows>
                <thead>
                    <tr>
                    <th>Class number</th>
                    <th>Reservation date</th>
                    <th>Time and booker</th>
                    </tr>
                </thead>
                <tbody>
                {% for key, attempts in overlapping.items %}
                <form method="POST"> {% csrf_token %}
                    <tr>
                        <td>{{ key.class_name.class_name }}</td>
                        <td>{{ key.reservation_date }}</td>
                        <td>
                            <label for="collisions"></label>
                            <select name="collisions" id="collisions">
                            {% for attempt in attempts %}
                                <option value="{{ attempt.reserved_by }};{{ attempt.time_start }};{{ attempt.time_end }}">
                                    {{ attempt.reserved_by }} hours: {{ attempt.time_start }} - {{ attempt.time_end }}
                                </option>
                            {% endfor %}
                            </select>
                        </td>
                        <td><input type="submit" value="accept" name="accept_button"></td>
                        <td> <input type="hidden" value="{{ key.class_name.class_name }};{{ key.reservation_date }}" name="collision_button"></td>
                    </tr>
                </form>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{#    #}
{#    #}
{#    #}
{#    {% for attempt in attempts %}#}
{#    {% endfor %}#}

{% endblock %}

ReservationServiceProject/ReservationService/templates/ReservationService/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Reservation Service{% endblock %}</title>
</head>
<style>
.footer {
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  background-color: grey;
  color: white;
  text-align: center;
}
</style>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
{% block footer %}
<div class="footer">
  <p>
      <a href="{% url 'ReservationService:home' %}">HOME</a>
  </p>
</div>
{% endblock %}
</body>
</html>

ReservationServiceProject/ReservationService/templates/ReservationService/booked_slots.html
<form method="POST">
    {% csrf_token %}
{{ form.as_p }}
<input type='submit' value='Search'>
</form>
<h1>
    Already booked terms: <br>
</h1>
{% if all_booked_slots %}

    {% for booked_slot in all_booked_slots %}
        {{ booked_slot }}<br>
    {% endfor %}
{% else  %}
    There is no class with this number or it's not occupied. Available class numbers: <br>
     {% for class_number in available_class %}
        {{ class_number }}<br>
    {% endfor %}
{% endif %}

ReservationServiceProject/ReservationService/templates/ReservationService/cal_base.html
<!-- ReservationService/templates/ReservationService/cal_base.html -->

{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'ReservationService/css/styles.css' %}">
  <title>Django Calendar App</title>
</head>
<body>

  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

ReservationServiceProject/ReservationService/templates/ReservationService/calendar_view.html
{% extends 'ReservationService/cal_base.html' %}

{% block title %}Calendar{% endblock %}

{% block content %}
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'ReservationService:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info right" href="{% url 'ReservationService:calendar' %}?{{ next_month }}"> Next Month </a>
</div>
    {{ calendar }}
{% endblock %}

ReservationServiceProject/ReservationService/templates/ReservationService/home.html
{% extends 'ReservationService/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    {% if not user.is_authenticated %}
        <h2> <a href="{% url 'ReservationService:login' %}"> Sign in </a></h2>
    {% else %}
        <a href="{% url 'ReservationService:profile' %}">Profile </a>
        <br>
        <a href="{% url 'ReservationService:reservation' %}">Reservation </a>
        <br>
        <a href="{% url 'ReservationService:accept' %}">Accept reservation attempts</a>
        <h2><a href="{% url 'ReservationService:logout' %}"> Logout </a> </h2>
    {% endif %}
    <br>
    <h1> Calendar</h1>
    {% for year, semesters in available_semesters %}
        {{ year}}
        <ul>
        {% for semester in semesters %}
            <li><a href="{% url 'ReservationService:calendar_view' year semester %}"> {{ semester }}</a> </li>
        {% endfor %}
        </ul>
    {% endfor %}
    {% if user.is_authenticated and user.is_staff%}
    <h1> <a href="{% url 'ReservationService:upload_csv' %}"> Upload Data </a> </h1>
    {% endif %}
{% endblock %}

{% block footer %}
{% endblock %}

ReservationServiceProject/ReservationService/templates/ReservationService/reservation.html
{% extends 'ReservationService/base.html' %}

{% block title %} Reservation {% endblock %}
{% block content %}
    <h2>You can reserve term here</h2>
    <form method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Search'>

    </form>
    <br>
    Available class: <br>
    {% for class_ in available_class %}
        <form method="POST"> {% csrf_token %}
            <input type="hidden" value="{{ form.data }}" name="additional_data">
            <input type="hidden" value="{{ class_.class_name }}" name="class">
            <label for="class_to_book">{{ class_ }}
            <input type="submit" name="class_to_book" ></label>
            <br>
        </form>
    {% endfor %}
     </form>
{% endblock %}

ReservationServiceProject/ReservationService/templates/ReservationService/upload_csv.html
{% extends 'ReservationService/base.html' %}

{% block title %}Upload{% endblock %}
{% block content %}
    <p>{{ message }}</p>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label>Upload csv</label><br>
        <input type="file" accept="text/csv" name="file"><br>
        <button type="submit">Submit</button>
    </form>
{% endblock %}